version: '3.9'

services:
  si-mongodb:
    image: mongo:latest
    ports:
    - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin-pass
    volumes:
    - mongo-db-data:/data/db
    - mongo-config-data:/data/configdb
  si-mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: si-root-pass
      MARIADB_DATABASE: si-database
      MARIADB_USER: si-user
      MARIADB_PASSWORD: si-user-pass
    ports:
    - "3306:3306"
    volumes:
    - mariadb_data:/var/lib/mysql
  # si-service-game-data:
  #   build: ./service-game-data/
  #   environment:
  #     NODE_ENV: development
  #     FILES_DB: "mongodb://admin:admin-pass@si-mongodb://si-mongodb:27017/?authSource=admin"
  #     SQL_HOST: "si-mariadb"
  #     SQL_PORT: 3306
  #     SQL_USER: si-user
  #     SQL_PASSWORD: si-user-pass
  #     SQL_DATABASE: si-database
  #     SQL_CONNECTION_LIMIT: 50
  #   ports:
  #   - "9000:8080"
  #   depends_on:
  #   - si-mongodb
  #   - si-mariadb

volumes:
  mongo-db-data:
  mongo-config-data:
  mariadb_data:
