version: '3.9'

services:
  si-mongodb:
    image: mongo:6.0
    ports:
    - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin-pass
    volumes:
    - mongo-db-data:/data/db
    - mongo-config-data:/data/configdb

volumes:
  mongo-db-data:
  mongo-config-data:
