# https://pnpm.io/settings
minimumReleaseAge: 10080
trustPolicyExclude:
  - 'chokidar@4.0.3'
  - 'semver@6.3.1'
trustPolicy: no-downgrade
blockExoticSubdeps: true
allowBuilds:
  argon2: set this to true or false
  esbuild: false
  sharp: false
  workerd: false
